#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
exec /usr/bin/env java -cp "$SCRIPT_DIR/conduit-kafka-connect-wrapper-0.1.0.jar:$SCRIPT_DIR/libs/*" io.conduit.Application
