#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
exec /usr/bin/env java \
	-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,quiet=y,address=*:5005 \
	-cp "$SCRIPT_DIR/conduit-kafka-connect-wrapper-0.3.0.jar:$SCRIPT_DIR/libs/*" \
	--add-opens=java.base/java.nio=ALL-UNNAMED \
		io.conduit.Application
